version: '3.5'

services:
  attacker:
    container_name: attacker
    build: ..
    restart: on-failure
    networks:
      - mynetwork
    command: tail -f /dev/null

  source:
    container_name: source
    build: ./targets
    restart: on-failure
    networks:
      - mynetwork
    command: tail -f /dev/null

  target:
    container_name: target
    build: ./targets
    restart: on-failure
    networks:
      - mynetwork
    command: tail -f /dev/null

networks:
  mynetwork:
    driver: bridge
